use core_logic::field_arith::FieldElement;
use core_logic::trapdoor::Trapdoor;
use core_logic::routing::{create_onion_packet, HydraNode, PAYLOAD_SIZE};
use core_logic::hydra_sss::{fragment_data, reconstruct_data};
use core_logic::anomality::{SelfHealingRouter, HoneypotManager};
use subtle::Choice;

struct XorShiftRng {
    state: u32,
}

impl XorShiftRng {
    fn new(seed: u32) -> Self {
        XorShiftRng { state: seed }
    }
}

impl hal_abstraction::SecureRandom for XorShiftRng {
    type Error = ();

    fn fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), Self::Error> {
        for byte in dest.iter_mut() {
            self.state = self.state.wrapping_mul(1103515245).wrapping_add(12345);
            *byte = (self.state >> 16) as u8;
        }
        Ok(())
    }
}

#[test]
fn test_hydra_darknet_complete_simulation() {
    let mut rng = XorShiftRng::new(0xABCDEF01);

    // =========================================================================
    // 1. SETUP: WEBPAGE FRAGMENTATION (SSS)
    // =========================================================================
    // We have a highly classified webpage that we want to host on 5 VPS nodes.
    // k = 3, n = 5. Any 3 of the 5 nodes can reconstruct the page.
    let webpage_bytes = b"<html><body><h1>HYDRA-ITS SECURE INDEX</h1></body></html>";
    let k = 3;
    let n = 5;

    let initial_shares = fragment_data(webpage_bytes, k, n, &mut rng).unwrap();
    assert_eq!(initial_shares.len(), 5);

    // =========================================================================
    // 2. SETUP: HYDRA ROUTING NODES AND TRAPDOORS
    // =========================================================================
    // We set up a mixnet of 4 active routing nodes + 1 Honeypot node + 1 Backup.
    // Each node has a unique FieldElement index (1..=6).
    // Let's define public points and private trapdoors for each node.
    let pub_pts = [
        (FieldElement::new(1), FieldElement::new(8)),   // Node 1
        (FieldElement::new(2), FieldElement::new(11)),  // Node 2
        (FieldElement::new(3), FieldElement::new(14)),  // Node 3
        (FieldElement::new(4), FieldElement::new(0)),   // Node 4 (Alternative/Failover)
        (FieldElement::new(5), FieldElement::new(3)),   // Node 5 (Honeypot Decoy)
    ];

    let trapdoor_1 = Trapdoor::<2>::new([(FieldElement::new(2), FieldElement::new(11)), pub_pts[0]]);
    let trapdoor_2 = Trapdoor::<2>::new([(FieldElement::new(1), FieldElement::new(8)), pub_pts[1]]);
    let trapdoor_3 = Trapdoor::<2>::new([(FieldElement::new(4), FieldElement::new(0)), pub_pts[2]]);
    let trapdoor_4 = Trapdoor::<2>::new([(FieldElement::new(3), FieldElement::new(14)), pub_pts[3]]);

    // Pre-shared or ratcheted MAC validation keys and nonces for each hop
    let mac_keys = [
        FieldElement::new(5),
        FieldElement::new(6),
        FieldElement::new(7),
        FieldElement::new(8),
    ];
    let nonces = [
        FieldElement::new(10),
        FieldElement::new(11),
        FieldElement::new(12),
        FieldElement::new(13),
    ];

    let node1 = HydraNode::new(FieldElement::new(1), trapdoor_1, mac_keys[0], nonces[0]);
    let node2 = HydraNode::new(FieldElement::new(2), trapdoor_2, mac_keys[1], nonces[1]);
    let node3 = HydraNode::new(FieldElement::new(3), trapdoor_3, mac_keys[2], nonces[2]);
    let _node4 = HydraNode::new(FieldElement::new(4), trapdoor_4, mac_keys[3], nonces[3]);

    // =========================================================================
    // 3. SECURE END-TO-END ONION ROUTING SIMULATION
    // =========================================================================
    // Alice wants to request a share from Node 1.
    // She routes her request over a 3-hop path: Alice -> Node 2 -> Node 3 -> Node 1.
    //
    // The routing indices for the onion layers:
    // - Hop 2 Index: Node 3 (index 3)
    // - Hop 3 Index: Node 1 (index 1)
    // - Final Destination: share retrieval command (e.g. index 9)
    let idx_hop2 = FieldElement::new(3);
    let idx_hop3 = FieldElement::new(1);
    let idx_dest = FieldElement::new(9);

    // Key material (k_pools) generated by Alice's TRNG for each hop encapsulation
    let k_pools = [
        FieldElement::new(12), // for Node 2 (Hop 1)
        FieldElement::new(13), // for Node 3 (Hop 2)
        FieldElement::new(14), // for Node 1 (Hop 3)
    ];

    // Secret query parameters (e.g., requesting webpage share part 1)
    let secret_query = [FieldElement::new(15), FieldElement::new(16)];

    // Alice creates the multi-hop onion packet
    let onion_packet = create_onion_packet(
        [pub_pts[1], pub_pts[2], pub_pts[0]], // Hops: Node 2, Node 3, Node 1
        k_pools,
        [mac_keys[1], mac_keys[2], mac_keys[0]],
        [nonces[1], nonces[2], nonces[0]],
        [idx_hop2, idx_hop3, idx_dest],
        &secret_query,
    );

    // Let's simulate the transmission over the hops
    // -- HOP 1 (Node 2) --
    let (next_hop_1, packet_to_hop2) = node2.process_packet(&onion_packet, 0, &mut rng).unwrap();
    assert_eq!(next_hop_1.value(), 3); // Node 2 correctly decapsulates and identifies next hop is Node 3!

    // -- HOP 2 (Node 3) --
    let (next_hop_2, packet_to_hop3) = node3.process_packet(&packet_to_hop2, 1, &mut rng).unwrap();
    assert_eq!(next_hop_2.value(), 1); // Node 3 correctly decapsulates and identifies next hop is Node 1!

    // -- HOP 3 (Node 1) --
    let (next_hop_3, decrypted_query_packet) = node1.process_packet(&packet_to_hop3, 2, &mut rng).unwrap();
    assert_eq!(next_hop_3.value(), 9); // Arrived at Node 1 successfully!

    // Node 1 processes decrypted query parameters:
    assert_eq!(decrypted_query_packet.payload[0].value(), 15);
    assert_eq!(decrypted_query_packet.payload[1].value(), 16);

    // =========================================================================
    // 4. CHAFF (DUMMY TRAFFIC) AND ANOMALY DETECTION SIMULATION
    // =========================================================================
    // Each node maintains an output stream with 100% constant packet rate.
    // If there is no real data in their queue, they generate dummy (chaff) packets.
    let mut node_with_queue = node1.clone();
    
    // Node 1 queue is empty initially -> pop_constant_rate_packet generates a dummy packet
    let dummy_packet1 = node_with_queue.pop_constant_rate_packet(&mut rng);
    let dummy_packet2 = node_with_queue.pop_constant_rate_packet(&mut rng);
    
    // To an observer, the size and formatting of dummy packets are identical to real ones!
    assert_eq!(dummy_packet1.payload.len(), PAYLOAD_SIZE);
    assert_eq!(dummy_packet2.payload.len(), PAYLOAD_SIZE);

    // We set up the SelfHealingRouter and Anomaly detectors
    let mut router = SelfHealingRouter::new();
    router.add_peer(FieldElement::new(1)); // Node 1
    router.add_peer(FieldElement::new(2)); // Node 2
    router.add_peer(FieldElement::new(3)); // Node 3
    router.add_peer(FieldElement::new(4)); // Node 4

    // Register Honeypot decoy indices
    let mut honeypot_mgr = HoneypotManager::new();
    honeypot_mgr.register_honeypot(FieldElement::new(5)); // Node 5 is a Honeypot Decoy

    // An attacker tries to retrieve data from Honeypot 5: triggers immediate alarm!
    let trigger_alert = honeypot_mgr.check_request(FieldElement::new(5));
    assert!(trigger_alert);
    assert_eq!(honeypot_mgr.alert_count, 1);

    // =========================================================================
    // 5. MITM ATTACK AND ANOMALY DETECTION
    // =========================================================================
    // An attacker (Eve) intercepts a packet between Node 2 and Node 3 and alters its Wegman-Carter header tag.
    let mut corrupted_packet = packet_to_hop2.clone();
    corrupted_packet.header_tags[1] = corrupted_packet.header_tags[1] + FieldElement::new(1); // Corrupt the tag!

    // Node 3 processes the packet. It evaluates its validity in constant-time.
    let is_tag_valid = core_logic::otm::verify_tag(
        node3.header_mac_key,
        corrupted_packet.header_points[1].1,
        node3.header_nonce,
        corrupted_packet.header_tags[1],
    );
    assert!(!bool::from(is_tag_valid)); // Tag validation fails!

    // Node 3's AnomalyDetector logs this failure:
    let is_anomaly_detected = router.peers[2].record_packet_arrival(100, is_tag_valid);
    assert!(!is_anomaly_detected); // First failure, not isolated yet

    // Attacker sends 2 more corrupt packets
    let _ = router.peers[2].record_packet_arrival(110, Choice::from(0));
    let is_isolated = router.peers[2].record_packet_arrival(120, Choice::from(0));
    
    // Node 3 has reached 3 integrity failures -> isolated from the network!
    assert!(is_isolated);
    assert!(router.peers[2].is_isolated);

    // =========================================================================
    // 6. ACTIVE SELF-HEALING REROUTING
    // =========================================================================
    // Since Node 3 is compromised and isolated, the router actively avoids it.
    // When Alice wants to send subsequent traffic through Node 3, the SelfHealingRouter
    // dynamically reroutes the hop through Node 4 (Alternative Mix) instead!
    let route_choice = router.get_healthy_route(FieldElement::new(3), &[FieldElement::new(4)]);
    assert_eq!(route_choice.value(), 4); // Rerouted successfully through Node 4!

    // =========================================================================
    // 7. HYDRA SHARE REGENERATION
    // =========================================================================
    // Since Node 3 (Mix and share host) went offline, we need to regenerate its lost share
    // onto a fresh Backup Node 6 to preserve the (3, 5) threshold webpage availability.
    //
    // We collect the healthy shares from Node 1, Node 2, and Node 4 (k=3 shares).
    let healthy_shares = vec![
        initial_shares[0].clone(), // Node 1
        initial_shares[1].clone(), // Node 2
        initial_shares[3].clone(), // Node 4
    ];

    let new_node_6_id = FieldElement::new(6);
    
    // Regenerate share for Node 6 mathematically via Lagrange interpolation on the active shares
    let regenerated_share = router.regenerate_share_for_new_node(
        &healthy_shares,
        FieldElement::new(3), // Failed Node 3
        new_node_6_id,        // New Node 6
        k,
        &mut rng,
    ).unwrap();

    assert_eq!(regenerated_share.id.value(), 6);

    // =========================================================================
    // 8. FINAL RECONSTRUCTION FROM HYDRA SHARE NETWORK
    // =========================================================================
    // Alice retrieves the shares from Node 1, Node 2, and the newly healed Node 6 (3 shares).
    let active_hydra_shares = vec![
        initial_shares[0].clone(), // Node 1
        initial_shares[1].clone(), // Node 2
        regenerated_share,         // Healed Node 6
    ];

    let final_reconstructed_webpage = reconstruct_data(&active_hydra_shares, k).unwrap();
    
    // Webpage successfully recovered!
    assert_eq!(final_reconstructed_webpage, webpage_bytes);
    println!("Simulation Successful! Hydra-ITS network healed itself and recovered the webpage!");
}
