#!/usr/bin/env bash
# ITS Operator Bundle — one-shot bootstrap + release build + PATH setup.
#
# Installs constitution trio on PATH: its-km, its-routing, its_asymmetric
# Optional: shell completions via install_completions.sh
#
# Usage:
#   ./scripts/its-operator-install.sh [ECOSYSTEM_ROOT]
#   ECOSYSTEM_ROOT defaults to parent of ROUTING (e.g. /home/user)
#
# After install:
#   source ~/.its/env.sh          # or add to ~/.bashrc
#   ./scripts/its-onboard.sh      # first-time operator wizard
#   ./scripts/verify_cli_completions.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROUTING="$(cd "$SCRIPT_DIR/.." && pwd)"
ECO_ROOT="$(cd "$ROUTING/.." && pwd)"
ECO="${1:-$ECO_ROOT}"
KM="${ITS_KM_DIR:-$ECO/ITS-KeyManagement}"
ASY="${ITS_ASYMMETRIC_DIR:-$ECO/ITS-asymmetric}"
ITS_BIN="${ITS_BIN_DIR:-$HOME/.its/bin}"
ITS_ENV="$HOME/.its/env.sh"
SKIP_BOOTSTRAP="${SKIP_BOOTSTRAP:-0}"
INSTALL_COMPLETIONS="${INSTALL_COMPLETIONS:-1}"

usage() {
  cat <<EOF
Usage: $0 [ECOSYSTEM_ROOT]

Build release binaries for the constitution trio and install under ~/.its/bin.

Environment:
  ECOSYSTEM_TAG=v2.0.0     Tag for bootstrap.sh (when repos missing)
  SKIP_BOOTSTRAP=1         Skip clone if repos already present
  INSTALL_COMPLETIONS=0    Skip shell completion install
  ITS_BIN_DIR=PATH         Install dir (default: ~/.its/bin)
  ITS_KM_DIR / ITS_ASYMMETRIC_DIR   Override sibling repo paths

After install:
  source ~/.its/env.sh
  its-onboard.sh           # from ROUTING/scripts (or full path)
  verify_cli_completions.sh

Docker alternative:
  ./deploy/docker/docker_build_all.sh
  docker compose -f deploy/docker/docker-compose.yml up -d pool-mirror
EOF
}

[[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && usage && exit 0

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "its-operator-install: missing required command: $1" >&2
    exit 1
  }
}

need_cmd cargo
need_cmd git

mkdir -p "$ITS_BIN" "$HOME/.its"

if [[ "$SKIP_BOOTSTRAP" != "1" ]]; then
  if [[ ! -d "$ECO/ROUTING" && ! -d "$ECO/ITS-ROUTING" ]]; then
    echo "=== Bootstrap ecosystem under $ECO ==="
    "$ROUTING/scripts/bootstrap.sh" "$ECO"
  fi
fi

# Resolve ROUTING path inside ecosystem tree.
if [[ -d "$ECO/ROUTING" ]]; then
  ROUTING="$ECO/ROUTING"
elif [[ -d "$ECO/ITS-ROUTING" ]]; then
  ROUTING="$ECO/ITS-ROUTING"
else
  echo "its-operator-install: no ROUTING tree under $ECO" >&2
  exit 1
fi

KM="${ITS_KM_DIR:-$ECO/ITS-KeyManagement}"
ASY="${ITS_ASYMMETRIC_DIR:-$ECO/ITS-asymmetric}"

for repo in "$KM" "$ASY"; do
  [[ -d "$repo" ]] || {
    echo "its-operator-install: missing repo: $repo (run bootstrap or set ITS_*_DIR)" >&2
    exit 1
  }
done

echo "=== Building its-routing (transport release) ==="
(cd "$ROUTING" && cargo build -p its_routing --release)

echo "=== Building its-km ==="
(cd "$KM" && cargo build --release --bin its-km)

echo "=== Building its_asymmetric ==="
(cd "$ASY" && cargo build --release --bin its_asymmetric \
  --features "bundle,parallel,std,compact-wire")

install -m 755 "$ROUTING/target/release/its-routing" "$ITS_BIN/its-routing"
install -m 755 "$KM/target/release/its-km" "$ITS_BIN/its-km"
install -m 755 "$ASY/target/release/its_asymmetric" "$ITS_BIN/its_asymmetric"

cat >"$ITS_ENV" <<EOF
# ITS Operator Bundle — generated by its-operator-install.sh
export PATH="$ITS_BIN:\$PATH"
export ITS_ECO_ROOT="$ECO"
export ITS_KM_DIR="$KM"
export ITS_ASYMMETRIC_DIR="$ASY"
EOF

if [[ "$INSTALL_COMPLETIONS" == "1" ]]; then
  echo "=== Installing shell completions (constitution trio) ==="
  ITS_KM_DIR="$KM" ITS_ASYMMETRIC_DIR="$ASY" \
    "$ROUTING/scripts/install_completions.sh" --constitution-only --all 2>/dev/null \
    || ITS_KM_DIR="$KM" ITS_ASYMMETRIC_DIR="$ASY" \
      "$ROUTING/scripts/install_completions.sh" --constitution-only
fi

# Convenience symlink for onboard wizard.
ln -sf "$ROUTING/scripts/its-onboard.sh" "$ITS_BIN/its-onboard" 2>/dev/null || true

echo ""
echo "=== ITS Operator Bundle installed ==="
echo "  Binaries: $ITS_BIN"
echo "  Activate:  source $ITS_ENV"
echo ""
echo "  its-routing:     $("$ITS_BIN/its-routing" --help 2>&1 | head -1 || echo ok)"
echo "  its-km:          $("$ITS_BIN/its-km" --help 2>&1 | head -1 || echo ok)"
echo "  its_asymmetric:  $("$ITS_BIN/its_asymmetric" --help 2>&1 | head -1 || echo ok)"
echo ""
echo "Next:"
echo "  source $ITS_ENV"
echo "  $ROUTING/scripts/its-onboard.sh"
echo "  $ROUTING/scripts/verify_cli_completions.sh"
