use alloc::vec::Vec;
use crate::field_arith::FieldElement;
use crate::trapdoor::lagrange_interpolate;
use hal_abstraction::SecureRandom;
use subtle::{Choice, ConditionallySelectable};
use zeroize::{Zeroize, ZeroizeOnDrop, Zeroizing};

/// A single node's initial share and transitions for the ITS SSS-Chained Time-Lock.
#[derive(Clone, Debug, Zeroize, ZeroizeOnDrop)]
pub struct NodeTimeLockPackage {
    /// The node's index (x-coordinate), 1-indexed.
    pub node_id: FieldElement,
    /// The initial share at epoch 0 (one FieldElement per byte of the message).
    pub initial_share: Vec<FieldElement>,
    /// The transitions for this node over time.
    /// `transitions[t][m]` is the transition value for epoch `t -> t+1` and byte `m`.
    pub transitions: Vec<Vec<FieldElement>>,
}

/// The complete SSS-Chained Time-Lock puzzle generated by Alice.
#[derive(Clone, Debug, Zeroize, ZeroizeOnDrop)]
pub struct SssTimeLock {
    /// The encrypted message payload (one FieldElement per byte of the message).
    /// Encrypted using the final epoch T secret as a One-Time Pad.
    pub encrypted_payload: Vec<FieldElement>,
    /// The packages for each node (1..=n).
    pub node_packages: Vec<NodeTimeLockPackage>,
}

/// Generates a random polynomial of degree `k-1` with the given `secret` as the constant term.
fn generate_random_poly<R: SecureRandom>(
    k: usize,
    secret: FieldElement,
    rng: &mut R,
) -> Result<Vec<FieldElement>, ()> {
    let mut coeffs = Vec::with_capacity(k);
    coeffs.push(secret);
    let mut buf = [0u8; 2];
    for _ in 1..k {
        rng.fill_bytes(&mut buf).map_err(|_| ())?;
        let val_raw = ((buf[0] as u16) | ((buf[1] as u16) << 8)) % 65521;
        let is_zero = Choice::from((val_raw == 0) as u8);
        let val_fe = FieldElement::new(val_raw);
        let non_zero_fe = FieldElement::conditional_select(&val_fe, &FieldElement::one(), is_zero);
        coeffs.push(non_zero_fe);
    }
    Ok(coeffs)
}

/// Evaluates a polynomial at a given point `x` using Horner's method.
fn evaluate_poly(coeffs: &[FieldElement], x: FieldElement) -> FieldElement {
    let k = coeffs.len();
    let mut result = coeffs[k - 1];
    for i in (0..k - 1).rev() {
        result = (result * x) + coeffs[i];
    }
    result
}

impl SssTimeLock {
    /// Generates a new SSS-Chained Time-Lock puzzle for a secret message.
    ///
    /// # Arguments
    /// * `message` - The raw secret bytes to lock in time.
    /// * `k` - The reconstruction threshold.
    /// * `n` - The total number of nodes.
    /// * `epochs` - The total number of steps/epochs $T$ the message is locked for.
    /// * `rng` - A secure random number generator.
    pub fn generate<R: SecureRandom>(
        message: &[u8],
        k: usize,
        n: usize,
        epochs: usize,
        rng: &mut R,
    ) -> Result<Self, ()> {
        if k == 0 || n < k || n >= 65521 || epochs == 0 || message.is_empty() {
            return Err(());
        }

        let len = message.len();

        // 1. Generate all random polynomials for all epochs and all bytes.
        // `polys[t][m]` is the polynomial (coefficients) for epoch `t` and byte `m`.
        let mut polys = Vec::with_capacity(epochs + 1);
        let mut buf = [0u8; 2];

        for _ in 0..=epochs {
            let mut epoch_polys = Vec::with_capacity(len);
            for _ in 0..len {
                // Generate a random secret for this polynomial
                rng.fill_bytes(&mut buf).map_err(|_| ())?;
                let secret_raw = ((buf[0] as u16) | ((buf[1] as u16) << 8)) % 65521;
                let secret = FieldElement::new(secret_raw);
                
                let poly = generate_random_poly(k, secret, rng)?;
                epoch_polys.push(poly);
            }
            polys.push(epoch_polys);
        }

        // 2. Encrypt the payload using the final epoch's secrets as One-Time Pads.
        // Formula: C_m = M_m + S_{m, T} mod 65521
        let mut encrypted_payload = Vec::with_capacity(len);
        for m in 0..len {
            let secret_t = polys[epochs][m][0]; // P_{m, T}(0)
            let msg_fe = FieldElement::new(message[m] as u16);
            encrypted_payload.push(msg_fe + secret_t);
        }

        // 3. Generate the initial shares for epoch 0 for each node.
        // `initial_shares[i][m]` is the share of node `i` (1-indexed) for byte `m` at epoch 0.
        let mut node_packages = Vec::with_capacity(n);
        for i in 1..=n {
            let node_id = FieldElement::new(i as u16);
            let mut initial_share = Vec::with_capacity(len);
            for m in 0..len {
                let share_val = evaluate_poly(&polys[0][m], node_id);
                initial_share.push(share_val);
            }

            // 4. Generate transitions for this node over all epochs.
            // `transitions[t][m]` is the transition for epoch `t -> t+1` and byte `m`.
            let mut transitions = Vec::with_capacity(epochs);
            for t in 0..epochs {
                let mut epoch_transitions = Vec::with_capacity(len);
                for m in 0..len {
                    let share_t = evaluate_poly(&polys[t][m], node_id);
                    let share_t_plus_1 = evaluate_poly(&polys[t + 1][m], node_id);
                    
                    // Formula: C_{m, i, t -> t+1} = P_{m, t+1}(i) + P_{m, t}(i) mod 65521
                    epoch_transitions.push(share_t_plus_1 + share_t);
                }
                transitions.push(epoch_transitions);
            }

            node_packages.push(NodeTimeLockPackage {
                node_id,
                initial_share,
                transitions,
            });
        }

        // Clean up intermediate polynomials securely
        for mut epoch_polys in polys {
            for poly in epoch_polys.iter_mut() {
                poly.zeroize();
            }
            epoch_polys.clear();
        }

        Ok(SssTimeLock {
            encrypted_payload,
            node_packages,
        })
    }
}

/// Transitions a node's share from epoch `t` to `t+1` using the transition values.
///
/// Formula: `next_share = transition_val - current_share mod 65521`
pub fn transition_share(
    current_share: &[FieldElement],
    transition_val: &[FieldElement],
) -> Result<Vec<FieldElement>, ()> {
    if current_share.len() != transition_val.len() {
        return Err(());
    }
    let mut next_share = Vec::with_capacity(current_share.len());
    for i in 0..current_share.len() {
        next_share.push(transition_val[i] - current_share[i]);
    }
    Ok(next_share)
}

/// Reconstructs the original secret message from the final epoch shares of at least `k` nodes.
///
/// # Arguments
/// * `encrypted_payload` - The encrypted ciphertext payload.
/// * `node_shares` - A slice of tuples containing `(node_id, final_share)` for at least `k` nodes.
/// * `k` - The reconstruction threshold.
pub fn reconstruct_time_lock(
    encrypted_payload: &[FieldElement],
    node_shares: &[(FieldElement, Vec<FieldElement>)],
    k: usize,
) -> Result<Vec<u8>, ()> {
    if node_shares.len() < k || encrypted_payload.is_empty() {
        return Err(());
    }

    let len = encrypted_payload.len();
    for &(_, ref share) in node_shares {
        if share.len() != len {
            return Err(()); // Mismatched share length
        }
    }

    let mut decrypted_message = Vec::with_capacity(len);

    // For each byte m of the message, perform Lagrange interpolation at x = 0
    for m in 0..len {
        let mut interpolation_points = Zeroizing::new(Vec::with_capacity(k));
        for i in 0..k {
            let (node_id, ref share) = node_shares[i];
            interpolation_points.push((node_id, share[m]));
        }

        // Interpolate at x = 0 to find the final secret S_{m, T}
        let secret_t = lagrange_interpolate(&*interpolation_points, FieldElement::zero());

        // Decrypt the byte: M_m = C_m - S_{m, T} mod 65521
        let decrypted_fe = encrypted_payload[m] - secret_t;
        decrypted_message.push(decrypted_fe.value() as u8);
    }

    Ok(decrypted_message)
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    struct SimpleRng {
        state: u32,
    }

    impl SecureRandom for SimpleRng {
        type Error = ();

        fn fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), Self::Error> {
            for byte in dest.iter_mut() {
                self.state = self.state.wrapping_mul(1103515245).wrapping_add(12345);
                *byte = (self.state >> 16) as u8;
            }
            Ok(())
        }
    }

    #[test]
    fn test_sss_chained_time_lock_roundtrip() {
        let mut rng = SimpleRng { state: 0xDEADBEEF };
        let message = b"ITS-Time-Lock-Secret-2026!";
        
        let k = 3;
        let n = 5;
        let epochs = 5;

        // 1. Alice generates the time-lock puzzle
        let puzzle = SssTimeLock::generate(message, k, n, epochs, &mut rng).unwrap();
        assert_eq!(puzzle.encrypted_payload.len(), message.len());
        assert_eq!(puzzle.node_packages.len(), n);

        // 2. Distribute packages to nodes and simulate transition over epochs
        // `current_shares[i]` holds the current share of node i
        let mut current_shares: Vec<Vec<FieldElement>> = puzzle
            .node_packages
            .iter()
            .map(|pkg| pkg.initial_share.clone())
            .collect();

        // Simulate stepping forward through each epoch
        for t in 0..epochs {
            for i in 0..n {
                let transition_val = &puzzle.node_packages[i].transitions[t];
                current_shares[i] = transition_share(&current_shares[i], transition_val).unwrap();
            }
        }

        // 3. Bob collects shares at epoch T from a subset of k nodes (e.g., nodes 0, 2, 4)
        let collected_shares = vec![
            (puzzle.node_packages[0].node_id, current_shares[0].clone()),
            (puzzle.node_packages[2].node_id, current_shares[2].clone()),
            (puzzle.node_packages[4].node_id, current_shares[4].clone()),
        ];

        // 4. Bob reconstructs the secret message
        let decrypted = reconstruct_time_lock(&puzzle.encrypted_payload, &collected_shares, k).unwrap();
        assert_eq!(decrypted, message);
    }
}
